### ISSUE TITLE
카카오 페이지에 들어갔을 때

### ISSUE THREAD

**Issue by ferrariRoma** [ferrariRoma/toonsoup#2]
# 바로 해당 사이트에 해당 요일 1,2,3위를 가져올지!
# 월, 화, 수, 목, 금, ... 이렇게 요일 별로 쭉 1,2,3위를 가져와서 배치를 할지
#### a,b,c,d를 보여줄지, 아니면 b,c,d만 보여주고 a는 DB에 뒀다가 다음에 순위에 a가 들면 그때 다시 꺼내올지. 아니면 아예 순위에서 벗어나면 삭제할지

**Comment by ddooyn** [comment]
날짜 받아와서 해당 요일 1,2,3위 보여주는게 화면상 깔끔할거 같아요!
그리고 번거롭긴 해도 DB에 데이터 쌓이는거 고려하면 가져올 때마다 데이터 삭제 후 교체하는게 좋을것 같습니다.
